# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Femi Joshua O
title: IT Solution Developer | System Administrator
email: femi-joshua@ichanneltech.com
# email_title: Email (Email title override)
phone: 234 (0) 803 065 5234
# phone_title: Official contact number
website: https://ichanneltech.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: femijoshuao
facebook_username: femijoshuao
instagram_username: femijoshuao
linkedin_username: femijoshuao

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/femijoshuao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me 
about_profile_image: images/femi-Joshua-circled-image.png
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Femi Joshua Olayiwola. I am a Technocrat, Social Entrepreneur, Realist, and Gospel Advocate. 
  I work with IChannel Technologies in Nigeria as a senior executive director. 
  In practice, I work as a solutions developer, designing programs, software, and network architecture to meet the needs of my clients. 
  I help my clients reach their objectives by developing IT solutions that address all of their requirements. 
  I've worked for a lot of firms, earning experience in teamwork and leadership.

  I am most skilled in Cloud services administration and <mark>eating pizza</mark> ðŸ•.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Enterprise Resources Planning (ERP) Solutions
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Implementation and deployment of ERPNext Software 
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/frappe/erpnext
        quote: >
          ERPNext is one of the most impressive enterprise business applications on which I have ever worked. 
          Because it is a Phyton application and an open source project, its simplicity and community of talented developers 
          assist in promptly resolving issues.
        description: | # this will include new lines to allow paragraphs
          This project began as a way for me to understand the Frappe Framework and to assist my customer in moving to a 
          digital business solution in order to achieve their objectives. This has taught me a lot of useful skills, and I'm pleased to have it in my portfolio. 
          If you're looking for a cost-effective business application that can replace SAP or SAGE and includes manageable modules such as Accounting, 
          Invoicing, Inventory, Manufacturing, Sales, Human Resources, and more, go no further. I'll gladly help you set it up on any cloud service 
          provider of your choosing. I also provided a managed solution for small businesses.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: IChannel Technologies
        sub_title: Senior Executive Officer
        caption: November 2010 - present
        link: https://ichanneltech.com
        quote: >
          IChannel Technologies is a global full-cycle software and information technology consulting company with niche expertise and a focus on the latest technologies. 
          Since 2010, we have been helping companies achieve their goals with impactful, industry-specific software and technology solutions
        description: | # this will include new lines to allow paragraphs
          - Develop and implement custom IT solutions that met business requirements of customers.
          - Oversee and performing administrative functions concerned with a project
          - Leading role in planning, executing, monitoring, controlling and closing projects
          - Project Outsourcing
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Ideal Konsult Limited
        sub_title: Network Administrator / Trainer
        caption: 2009
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          - Instruct Cisco , Microsoft, Security and System Administration Courses
          - Developed Cisco and Microsoft training curriculum for Idea Konsult IT Training Center
          - Managing the networking system and ensuring adequate network security
          - Site Technician for Pearson VUE and Thomson Prometric Testing Center
  - title: Capabilities and skills
    layout: text
    content: | # this will include new lines to allow paragraphs
       - Understand the country information and technology communication business strategies
      - Open Minded, the ability to understand, handle any new technologies in a short time
      - Providing expedient error corrections and solutions whilst working on projects in a variety of support and development roles.
      - Highly Intellectual in use of Computer and well experienced in using most application and system software
      - Excellent in website and web application designing using content management 
      - Understanding Complex network, such as IP, IGRP, IP RIP, asynchronous routing, Apple Talk, Extended 
      access-list, route redistribution, IPX RIP, route summarization, OSPF, VLSM, Serial IGRP, VLAN, Ethernet access-list 802.10
      - Technically skilled in Remote Troubleshooting
      - Exceptional skill in the use and deployement of Open source software
      -  Able to work on Switches (Cisco, Mikrotik, AirLive), Routers (Cisco, Mikrotik, Ubiquiti), Wireless (Cisco, Ubiquiti, Mikrotik Cisco PIX Firewall
# Footer
footer_show_references: true
references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
